version: '2'
services:
  db:
    image: users_service_db
    volumes:
      - docker_practice:/var/lib/mysql
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: users_service
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: users
    expose:
      - "3306"
    ports:
      - "6002:3306"
volumes:
  docker_practice: